# Generated by Django 5.1.7 on 2025-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_payment_slot_alter_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_location',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Country_of_Birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Place_of_Birth',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
