# Generated by Django 5.1.5 on 2025-03-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='Booking_Fee',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
